services:
  mellon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mellon
    environment:
      
    volumes:
      # Map the models we moved to your local project folder
      - /home/jeyamir/Mellon/cache:/app/cache
      # Optional: folder for your own custom models
      - /home/jeyamir/Mellon/Models:/app/Models
    networks:
      - coolify
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.routers.mellon.rule=Host(`mellon.jeyamir.lab`)"
      - "traefik.http.routers.mellon.entrypoints=http"
      # Updated to 8088 based on Mellon's startup logs
      - "traefik.http.services.mellon.loadbalancer.server.port=8088"

networks:
  coolify:
    external: true